### ISSUE TITLE
build as node module

### ISSUE THREAD

**Issue by jstncno** [bumrush/mentionify#12]
grunt is throwing errors when trying to build/test:
```
$ grunt
Running "jshint:files" (jshint) task
>> 3 files lint free.

Running "concat:dist" (concat) task
File dist/mentionify.js created.

Running "concat:test" (concat) task
File lib/qunit.js created.

Running "qunit:files" (qunit) task
Testing example.html
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.

Aborted due to warnings.
```

i've gotten into the habit of using npm scripts to build and test anyways, so i want to move on to that to replace grunt

**Comment by jstncno** [comment]
proposed new build and test workflow:

babelify (es6) -> webpack (build)  + mocha + jsdom (test) -> uglifyjs (compress)

**Comment by earthican** [comment]
we don't even need webpack!
