### ISSUE TITLE
Would it not be clearer if it is said 'site' instead of 'account'?

### ISSUE THREAD

**Issue by YazeedAlsaif** [bumrush/mentionify#7]
Hello

in the documentation it says: http://account.com/username to mean something like http://twitter.com/username. I think it might be clearer if it was http://site.com/username or http://example.com/username

Anyway, thanks! :)

**Comment by jstncno** [comment]
Ah, yes it would be more clear! I do prefer `site` over `account` :smile: 

Since this would be a backward incompatible API change, I will keep this open and change it for a future release. You are also more than welcome to create a pull request and I will merge it for the release :wink:
