### ISSUE TITLE
More flexibility in supported sites

### ISSUE THREAD

**Issue by OJFord** [bumrush/mentionify#9]
Rather than provide the `account` for `http://account.com/username`, would it not be more flexible to provide the entire `base-url` for `<base-url><username>`?

This way the full path including `+` could be provided for Google Plus for example, and TLDs other than `com` could be used.

**Comment by jstncno** [comment]
This is great, more flexibility is definitely a good thing. I'll work on this ticket to allow the user to specify the `base-url`, with the default being something like `http://<account>.com`.
